name: Azure Static Web Apps CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          api_location: ""
          app_artifact_location: "dist"

      - name: Determine version
        id: version
        run: echo "VERSION=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Create GitHub Release (and tag)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Automated release created by workflow run ${{ github.run_number }}.
            Commit: ${{ github.sha }}
            Run: ${{ github.run_id }}

